### ISSUE TITLE
VQCLRDLL Not Found

### ISSUE THREAD

**Issue by vimiani** [derplayer/PDN-FileTypePVR#1]
When saving or previewing a VQ format image, I get an exception about either VQCLRDLL or vqclrdll.dll not being found. Other data formats preview and save fine, but VQ does not. This tool with the same paint.net version worked fine on my previous install of Windows, so I'm not sure what would be going on here.

This also happens on a completely fresh Windows 7 VM. The logs point to a Costura folder in the temp files, I have confirmed the .dll is in fact there when you look in Explorer, and the .dll doesn't seem to be all 0s in a hex editor.

I don't know if I'm missing some sort of dependency that I had on my old install, it would be appreciated if I am to include a list of needed dependencies in the readme.

This has been tested on both 4.2.16 and 4.3.10, both throw the same error.
	
I have included the error reports when both previewing a VQ image and also trying to save one.
[previewing.txt](https://github.com/derplayer/PDN-FileTypePVR/files/8746127/previewing.txt)
[saving.txt](https://github.com/derplayer/PDN-FileTypePVR/files/8746128/saving.txt)

**Comment by derplayer** [comment]
Hmm...

https://github.com/derplayer/PDN-FileTypePVR/tree/master/PvrFiletype/costura64 Try to put it beside the plugin, could work.

I testes it on Win 10 x64 so it should work without any problems on modern OS.

The 1.0 plugin should work without cotsura errors but it has broken write support.

**Comment by AGraber** [comment]
`vqclrdll.dll` is built with the debug version of the C++ 2015 runtime VCRUNTIME140**D**.dll (note D at the end), so it won't work on PCs that don't have Visual Studio with the build tools of C++ 2015 installed or the debug runtimes copied and pasted from another machine.

![image](https://user-images.githubusercontent.com/18301034/169630498-ca55824a-e0d4-477d-ad24-5a3ddcce9acf.png)

Could you rebuild it with a normal Release runtime?

**Comment by derplayer** [comment]
@AGraber Danke dir für den tipp!

@vimiani Can you test this version?
[PdnPvrFiletype 1.1a.zip](https://github.com/derplayer/PDN-FileTypePVR/files/8746212/PdnPvrFiletype.1.1a.zip)

**Comment by vimiani** [comment]
> @AGraber Danke dir für den tipp!
> 
> @vimiani Can you test this version? [PdnPvrFiletype 1.1a.zip](https://github.com/derplayer/PDN-FileTypePVR/files/8746212/PdnPvrFiletype.1.1a.zip)

Seems to preview and save VQ images just fine now. Thank you!
I had Visual Studio installed on my old install of Windows, so that's definitely why I had no trouble with this before my reinstall.

**Comment by vimiani** [comment]
![Berserk - Sennen Teikoku no Taka-hen - Soushitsu Hana no Shou v1 001 (1999)(ASCII)(JP) ! -220520-220134](https://user-images.githubusercontent.com/58193812/169632926-590fc1c0-ad34-4867-8a57-2763f8cb4825.png)
Have also confirmed VQ images that are created with this new version still load in at least this game just in case.

**Comment by derplayer** [comment]
Great, i will then close this and release it officially.
